ENV["TWITTER_API_KEY"] = "4QhFWrHOHti3NCpzyXWPEWH9S"
ENV["TWITTER_API_SECRET"] = "kltQq8AmwSSoNigNlk7MUPqM5zWPrNCR1cgfxhlWwlKJbWFZ19"

ENV["TWITTER_ACCESS_TOKEN"] = "398471310-RES7sRpSpJWZ5LZLiCUUHiaGKRO3QjNCDqy36sv0"
ENV["TWITTER_ACCESS_TOKEN_SECRET"] = "ayBE0gLPxHrYaTSLtdJbITQSUPRTf0PBzhpBn4yxcrBcu"

